# Generated by Django 5.2.4 on 2025-07-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fb_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=20)),
                ('acad_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq', models.BooleanField(default=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('q_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('q_desc', models.TextField()),
                ('q_type', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('acad_year', models.CharField(max_length=10)),
                ('part', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.department'),
        ),
        migrations.CreateModel(
            name='FeedbackQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=200)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedbackquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('pgm_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pgm_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='pgm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.programme'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('fb_active', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBatch',
            fields=[
                ('teacher_batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFeedbackResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_id', models.CharField(blank=True, max_length=10, null=True)),
                ('ans_desc', models.TextField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('fb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedback')),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedbackquestion')),
                ('teacher_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.teacherbatch')),
            ],
        ),
    ]
