# Generated by Django 3.2.12 on 2025-07-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='pgm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
