# Generated by Django 4.1.5 on 2025-07-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0005_auto_20250730_2233"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherbatch",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback_app.course",
            ),
            preserve_default=False,
        ),
    ]
