# Generated by Django 3.2.12 on 2025-07-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_teacherbatch_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherbatch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.department'),
            preserve_default=False,
        ),
    ]
