# Generated by Django 5.0.1 on 2025-08-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0007_teacherbatch_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeedbackResponse",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=100)),
                ("feedback_number", models.IntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback_app.feedbackquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback_app.feedbackqoption",
                    ),
                ),
            ],
            options={
                "db_table": "student_feedback_response",
                "ordering": ["feedback_number", "question__q_id"],
            },
        ),
    ]
