# Generated by Django 5.0.1 on 2025-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0008_studentfeedbackresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="fb_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="feedbackquestion",
            name="q_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
