# Generated by Django 3.2.12 on 2025-08-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0009_alter_feedback_fb_id_alter_feedbackquestion_q_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedbackresponse',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.teacher'),
        ),
    ]
