# Generated by Django 5.1.5 on 2025-08-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0010_studentfeedbackresponse_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programme',
            name='pgm_name',
            field=models.CharField(max_length=200),
        ),
    ]
