# Generated by Django 4.2.11 on 2025-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0012_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
