# Generated by Django 5.1.5 on 2025-08-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0013_feedbackquestion_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfeedbackresponse',
            name='teacher_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.teacherbatch'),
        ),
        migrations.AddField(
            model_name='teacherbatch',
            name='is_active_for_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='teacherbatch',
            unique_together={('teacher', 'batch', 'course', 'department')},
        ),
    ]
