# Generated by Django 5.1.5 on 2025-08-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0014_batch_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedbackresponse',
            name='teacher',
        ),
    ]
